import { createStitches } from '@stitches/react';
import { colors } from '../../tokens/colors';
import { typography } from '../../tokens/typography';
import { spacing } from '../../tokens/spacing';

export const {
  styled,
  css,
  globalCss,
  keyframes,
  getCssText,
  theme,
  createTheme,
  config,
} = createStitches({
  theme: {
    colors: {
      primary100: colors.indigo[50],
      primary200: colors.indigo[500],
      primary300: colors.indigo[600],
      primary400: colors.indigo[700],

      success100: colors.green[50],
      success200: colors.green[500],
      success300: colors.green[600],
      success400: colors.green[700],

      info100: colors.cyan[50],
      info200: colors.cyan[500],
      info300: colors.cyan[600],
      info400: colors.cyan[700],

      warning100: colors.orange[50],
      warning200: colors.orange[500],
      warning300: colors.orange[600],
      warning400: colors.orange[700],

      danger100: colors.red[50],
      danger200: colors.red[500],
      danger300: colors.red[600],
      danger400: colors.red[700],

      neutral25: colors.white,
      neutral50: colors.greyBlue[50],
      neutral100: colors.greyBlue[100],
      neutral200: colors.greyBlue[200],
      neutral300: colors.greyBlue[300],
      neutral400: colors.greyBlue[500],
      neutral500: colors.greyBlue[700],

      neutralA25: colors.whiteAlpha,
      neutralA50: colors.greyBlueAlpha[50],
      neutralA100: colors.greyBlueAlpha[100],
      neutralA200: colors.greyBlueAlpha[200],
      neutralA300: colors.greyBlueAlpha[300],
      neutralA400: colors.greyBlueAlpha[500],
      neutralA500: colors.greyBlueAlpha[700],

    },
    space: {
      xs4: spacing[2],
      xs3: spacing[4],
      xs2: spacing[6],
      xs: spacing[8],
      s: spacing[12],
      m: spacing[16],
      l: spacing[20],
      xl: spacing[24],
      xl2: spacing[32],
      xl3: spacing[40],
      xl4: spacing[48],
    },
    fontSizes: {
      hero: typography.size[56],
      h1: typography.size[40],
      h2: typography.size[32],
      h3: typography.size[24],
      h4: typography.size[20],
      h5: typography.size[18],
      h6: typography.size[16],
      large: typography.size[18],
      medium: typography.size[16],
      small: typography.size[14],
      subLabel: typography.size[12],
      support: typography.size[12],
      monospace: typography.size[14],
    },
    fonts: {
      base: typography.family.base,
      heading: typography.family.heading,
      monospace: typography.family.monospace,
    },
    fontWeights: {
      regular: typography.fontWeight.regular,
      medium: typography.fontWeight.medium,
      bold: typography.fontWeight.bold,
    },
    lineHeights: {
      hero: typography.lineHeight[72],
      h1: typography.lineHeight[48],
      h2: typography.lineHeight[40],
      h3: typography.lineHeight[32],
      h4: typography.lineHeight[24],
      h5: typography.lineHeight[24],
      h6: typography.lineHeight[24],

      large: typography.lineHeight[24],
      medium: typography.lineHeight[24],
      small: typography.lineHeight[20],
      subLabel: typography.lineHeight[16],
      support: typography.lineHeight[16],
      monospace: typography.lineHeight[20],
    },
    letterSpacings: {},
    sizes: {
      xs4: spacing[2],
      xs3: spacing[4],
      xs2: spacing[6],
      xs: spacing[8],
      s: spacing[12],
      m: spacing[16],
      l: spacing[20],
      xl: spacing[24],
      xl2: spacing[32],
      xl3: spacing[40],
      xl4: spacing[48],
    },
    borderWidths: {
      none: 0,
      '1px': spacing[1],
      '2px': spacing[2],
      '4px': spacing[4],
      '8px': spacing[8],
    },
    borderStyles: {},
    radii: {
      none: '0',
      xs: spacing[2],
      s: spacing[4],
      m: spacing[8],
      l: spacing[16],
      xl: spacing[24],
      xl2: spacing[32],
      xl3: spacing[48],
      full: '9999px',
    },
    shadows: {},
    zIndices: {
      hide: -1,
      auto: 'auto',
      base: 0,
      docked: 10,
      dropdown: 1000,
      sticky: 1100,
      banner: 1200,
      overlay: 1300,
      modal: 1400,
      popover: 1500,
      skipLink: 1600,
      toast: 1700,
      tooltip: 1800,
    },
    transitions: {},
  },
});
