name: New version
run-name: CI
on:
  push:
    tags:
      - 'v*'
jobs:
  Call-CI-workflow:
    uses: ./.github/workflows/CI.yml
  Say-OK:
    runs-on: ubuntu-latest
    steps:
      - run: echo "OK"

