name: New version
run-name: CI
on:
  push:
    tags:
      - 'v*'
jobs:
  Call-CI-workflow:
    uses: ./.github/workflows/CI.yml
  Publish-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Configure npm access
        run: |
          cat >.npmrc <<END
          //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          END
        env:
          $NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node modules
        run: yarn install --immutable
      - name: Stash changes
        run: git stash
      - name: Publish package
        run: lerna publish from-git --yes
